    (defun busca (lista)
    (princ(car lista))
    (princ " ")
    (if (not (null lista)) 
        (busca (cdr lista))
    )
    (format t "~%")
    (princ "dame un numero a buscar ")
    (setq x(read))
    (if ( member x lista) (princ "Si esta el numero")
    (princ "no existe el numero"))
    )